apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-and-push
spec:
  workspaces:
    - name: source
  params:
    - name: IMAGE
  steps:
    - name: build
      image: quay.io/buildah/stable
      securityContext:
        privileged: true
      script: |
        buildah bud -t $(params.IMAGE) .
        buildah push $(params.IMAGE)
